apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name .Values.env }}
  labels:
    {{- include "sales-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
      name: http
  selector:
    {{- include "sales-api.selectorLabels" . | nindent 4 }}
