name: Lint Code Base

on:
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.ref_name == 'main' && 'prod' || startsWith(github.ref_name, 'release-') && 'qa' || 'dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_CSHARP: ${{ vars.VALIDATE_CSHARP }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
